---
- name: Pull and Deploy Docker Container from Docker Hub
  hosts: node
  become: true
  vars:
    dockerhub_image: "vishnupriyalnm/bankingdemo:1"
    container_name: "bankingdemo"
    container_port: 8081

  tasks:
    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ dockerhub_image }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ dockerhub_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ container_port }}:8080"
