---
- name: FinanceMe
  hosts: app_servers
  become: yes

  vars:
    image_name: vishnupriyalnm/bankingdemo
    image_tag: "1"
    container_name: banking_demo
    app_port: "8081"    # <--- NEW PORT

  tasks:

    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Stop existing container if running
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        ports:
          - "{{ app_port }}:8080"
        state: started
